### ISSUE TITLE
Quick introduction?

### ISSUE THREAD

**Issue by justJUH** [patriceckhart/NeosRulez.ShoppingCart#1]
Is there anywhere a quick introduction that I can read? I've successful installed the package but I'm pretty new at the development of software, so it whould be very helpful if there is an description how to go on from that point. Thanks.

**Comment by patriceckhart** [comment]
It works almost out-of-the-box. First look at the Settings.yaml of the package. All necessary settings you can write in the Settings.yaml of your own site package. It is important that you define the identifiers for shipping and the default country (first create in the Neos backend - the identifiers are visible in the table in the neos backend).

**Comment by justJUH** [comment]
We use Neos 3.3. Is there any difference to newer or older versions?

**Comment by patriceckhart** [comment]
The package is already optimized for Neos 4.1 but should also run at 3.3. However, version 1.5 should be able to cope with Neos 3.3 (the last version I have tested with 3.3).

If you need support, I need access to your project. Mail me (address in my github profil).
